// Complete tool catalog from all 6 Xtreme packages.
// Each tool is categorized by its source package and has a description,
// icon, and the backend function or integration it maps to.

export const TOOL_CATEGORIES = [
  {
    id: "cloud-browser",
    name: "Cloud Browser",
    icon: "Globe",
    color: "blue",
    description: "Cloud browser automation, captcha solving, SERP measurement, and proxy management.",
    tools: [
      { name: "Scheduled Browser Jobs", description: "Schedule and run browser automation jobs on the cloud.", function: "runScheduledJob", icon: "Clock" },
      { name: "Captcha Solver (Vision)", description: "AI-powered captcha solving using vision models.", function: "solveCaptchaVision", icon: "Eye" },
      { name: "Sandbox Manager", description: "Manage isolated browser sandbox sessions.", function: "sandboxManager", icon: "Box" },
      { name: "MCP Tools", description: "Model Context Protocol tool integration.", function: "mcpTools", icon: "Plug" },
      { name: "SERP Measurement", description: "Measure search engine result positions.", function: "serpMeasurement", icon: "Search" },
      { name: "Capability Validator", description: "Validate browser capabilities and features.", function: "validateCapabilities", icon: "CheckCircle" },
      { name: "Intelligent Retry", description: "Smart retry logic for failed browser scrapes.", function: "intelligentRetry", icon: "RefreshCw" },
      { name: "Browser Project Creator", description: "Create and configure browser automation projects.", function: "createProject", icon: "FolderPlus" },
      { name: "Profile Saver", description: "Save and manage browser session profiles.", function: "saveProfile", icon: "Save" },
      { name: "Master Release Suite", description: "Run the full master release test suite.", function: "runMasterReleaseSuite", icon: "Rocket" },
    ],
  },
  {
    id: "autoleads",
    name: "Auto Leads",
    icon: "Users",
    color: "green",
    description: "Automated lead generation, source discovery, lead scoring, and AI email responses.",
    tools: [
      { name: "Browser Scraper", description: "Scrape leads from web sources automatically.", function: "browserScrape", icon: "Scan" },
      { name: "Source Discovery", description: "Discover new lead generation sources.", function: "discoverSources", icon: "Compass" },
      { name: "Claim Auditor", description: "Audit and validate lead claims.", function: "auditClaims", icon: "ShieldCheck" },
      { name: "Portal Session Creator", description: "Create secure portal sessions for leads.", function: "createPortalSession", icon: "Key" },
      { name: "AI Email Response", description: "AI-powered automatic email responses.", function: "aiEmailResponse", icon: "Mail" },
      { name: "Calendar Sync", description: "Sync projects to Google Calendar.", function: "syncProjectToCalendar", icon: "Calendar" },
      { name: "Benchmark Research", description: "Run benchmark research on lead sources.", function: "runBenchmarkResearch", icon: "BarChart" },
      { name: "Federal API Scraper", description: "Scrape data from federal APIs.", function: "scrapeFederalAPIs", icon: "Landmark" },
      { name: "Source Quality Scorer", description: "Score the quality of lead sources.", function: "scoreSourceQuality", icon: "Star" },
      { name: "Lead Alert Pusher", description: "Push real-time alerts for new leads.", function: "pushNewLeadAlerts", icon: "Bell" },
    ],
  },
  {
    id: "xtremevisualizer",
    name: "Xtreme Visualizer",
    icon: "Eye",
    color: "amber",
    description: "Floor visualization, proposal building, pricing engine, and close-package generation.",
    tools: [
      { name: "Proposal Builder", description: "Build detailed proposals with line items, discounts, and warranties.", function: "proposalBuilder", icon: "FileText" },
      { name: "Pricing Engine", description: "Preliminary non-binding pricing range calculation.", function: "pricingEngine", icon: "DollarSign" },
      { name: "Close Engine", description: "Good/Better/Best tier package generation.", function: "closeEngine", icon: "Trophy" },
      { name: "Floor Specs", description: "Floor system specifications and configurations.", function: "floorSpecs", icon: "Layers" },
      { name: "Google Sheet Sync", description: "Sync leads to Google Sheets.", function: "syncLeadsToGoogleSheet", icon: "Sheet" },
      { name: "AI Floor Visualizer", description: "AI-powered floor color and finish visualization.", function: "GenerateImage", icon: "Wand2" },
    ],
  },
  {
    id: "xtreme-comms",
    name: "Xtreme Comms",
    icon: "MessageSquare",
    color: "purple",
    description: "Full production-grade AI voice, SMS, MMS, WhatsApp, email, and video communication with CRM.",
    tools: [
      { name: "Voice Orchestrator", description: "AI voice call orchestration and loop management.", function: "orchestrateVoiceLoop", icon: "Phone" },
      { name: "Call Gateway", description: "Voice call gateway with Telnyx integration.", function: "gatewayCalls", icon: "PhoneCall" },
      { name: "SMS/MMS Gateway", description: "Send and receive SMS/MMS messages.", function: "gatewayMessages", icon: "MessageSquare" },
      { name: "Email Gateway", description: "Send and manage email communications.", function: "gatewayEmail", icon: "Mail" },
      { name: "Video Gateway", description: "Video communication gateway.", function: "gatewayVideo", icon: "Video" },
      { name: "WhatsApp Gateway", description: "WhatsApp business messaging.", function: "gatewayMessages", icon: "MessageCircle" },
      { name: "Campaign Outreach", description: "Manage multi-channel campaign outreach.", function: "manageCampaignOutreach", icon: "Megaphone" },
      { name: "Conversation Orchestrator", description: "Orchestrate multi-turn conversations.", function: "orchestrateConversation", icon: "MessagesSquare" },
      { name: "Phone Number Manager", description: "Purchase and manage phone numbers.", function: "managePhoneNumbers", icon: "Phone" },
      { name: "Telnyx Provisioning", description: "Provision Telnyx communication resources.", function: "provisionTelnyxResources", icon: "Server" },
      { name: "Lead Enrichment", description: "Enrich leads with additional data.", function: "enrichLead", icon: "UserPlus" },
      { name: "Company Intelligence", description: "Scrape company intelligence data.", function: "scrapeCompanyIntelligence", icon: "Building" },
      { name: "Call Recording Manager", description: "Manage call recordings and transcripts.", function: "manageCallRecording", icon: "Disc" },
      { name: "Usage Metering", description: "Meter and track communication usage.", function: "meterUsage", icon: "Gauge" },
      { name: "User Replica Creator", description: "Create AI replicas of users for campaigns.", function: "createUserReplica", icon: "Copy" },
      { name: "Replica Campaign Runner", description: "Run campaigns with AI user replicas.", function: "runReplicaCampaign", icon: "Play" },
      { name: "Voice Preview", description: "Preview AI voice before deployment.", function: "previewVoice", icon: "Volume" },
      { name: "Workflow Engine", description: "Execute communication workflow engines.", function: "executeWorkflowEngine", icon: "Workflow" },
      { name: "Creative Media Generator", description: "Generate creative media for campaigns.", function: "generateCreativeMedia", icon: "Image" },
      { name: "MMS Creative Generator", description: "Generate MMS creative assets.", function: "generateMmsCreative", icon: "ImagePlus" },
      { name: "Communication Suite Generator", description: "Generate full communication suites.", function: "generateCommunicationSuite", icon: "Package" },
      { name: "HubSpot Sync", description: "Sync communications to HubSpot CRM.", function: "syncHubspot", icon: "RefreshCw" },
      { name: "Google Workspace Sync", description: "Sync with Google Workspace.", function: "googleWorkspaceSync", icon: "Calendar" },
      { name: "Autonomous Audit", description: "Run autonomous compliance audits.", function: "runAutonomousAudit", icon: "ShieldCheck" },
      { name: "Preflight Heal", description: "Preflight health checks and healing.", function: "preflightHeal", icon: "HeartPulse" },
    ],
  },
  {
    id: "seo-generator",
    name: "SEO Generator",
    icon: "TrendingUp",
    color: "emerald",
    description: "SEO content generation, technical audits, competitor monitoring, and ranking prediction.",
    tools: [
      { name: "Content Generator", description: "Generate SEO-optimized content automatically.", function: "ContentGenerator", icon: "PenLine" },
      { name: "SEO Content Rewriter", description: "Rewrite existing content for SEO.", function: "RewriteContentForSeo", icon: "Edit" },
      { name: "Headline Generator", description: "Generate compelling SEO headlines.", function: "GenerateHeadlines", icon: "Heading" },
      { name: "Copy Variants", description: "Generate A/B test copy variants.", function: "GenerateCopyVariants", icon: "Copy" },
      { name: "Technical SEO Audit", description: "Full technical SEO audit.", function: "TechnicalSeoAudit", icon: "SearchCheck" },
      { name: "Core Web Vitals Monitor", description: "Monitor Core Web Vitals metrics.", function: "CoreWebVitalsMonitor", icon: "Gauge" },
      { name: "Competitor Watchdog", description: "Monitor competitors automatically.", function: "CompetitorWatchdog", icon: "Eye" },
      { name: "Deep Discovery Scan", description: "Deep scan for SEO opportunities.", function: "DeepDiscoveryScan", icon: "Radar" },
      { name: "Predictive Ranking Model", description: "Predict search rankings with AI.", function: "PredictiveRankingModel", icon: "TrendingUp" },
      { name: "A/B Test Runner", description: "Run SEO A/B tests.", function: "ABTestRunner", icon: "FlaskConical" },
      { name: "Weekly Digest", description: "Generate weekly SEO digest reports.", function: "WeeklyDigest", icon: "FileText" },
      { name: "Client Reports", description: "Send automated client SEO reports.", function: "SendClientReports", icon: "Send" },
      { name: "Industry Knowledge Scraper", description: "Scrape industry knowledge for content.", function: "ScrapeIndustryKnowledge", icon: "BookOpen" },
      { name: "Authority Builder", description: "Build cross-domain authority.", function: "CrossDomainAuthorityBuilder", icon: "Link" },
      { name: "Security Scanner", description: "Scan for security issues.", function: "SecurityScan", icon: "Shield" },
      { name: "Auto Healing", description: "Auto-heal SEO issues with escalation.", function: "AutoHealingEscalation", icon: "Wrench" },
      { name: "Master Orchestrator", description: "Orchestrate all SEO systems.", function: "MasterOrchestrator", icon: "Orbit" },
      { name: "Search Console Sync", description: "Sync with Google Search Console.", function: "SyncSearchConsole", icon: "RefreshCw" },
    ],
  },
  {
    id: "xtremeos",
    name: "Xtreme OS",
    icon: "Cpu",
    color: "stone",
    description: "The master operating system — website factory, app factory, national launch, and tool orchestration.",
    tools: [
      { name: "Website Factory", description: "Turn this site into a template and generate new variants.", function: "websiteFactory", icon: "Factory" },
      { name: "App Factory", description: "Generate PWA mobile apps with bottom navigation.", function: "appFactory", icon: "Smartphone" },
      { name: "National Launch", description: "Deploy sites across cities and states nationally.", function: "nationalLaunch", icon: "Rocket" },
      { name: "Tool Orchestrator", description: "Orchestrate all tools from a single dashboard.", function: "toolOrchestrator", icon: "Orbit" },
      { name: "System Memory", description: "Persistent system memory and context.", function: "systemMemory", icon: "Database" },
      { name: "Deep Executor", description: "Execute deep autonomous tasks.", function: "deepExecutor", icon: "Zap" },
    ],
  },
];

export const ALL_TOOLS = TOOL_CATEGORIES.flatMap((cat) =>
  cat.tools.map((t) => ({ ...t, category: cat.id, categoryName: cat.name }))
);