// ═══════════════════════════════════════════════════════════════════════════
// agentTaxonomy.ts
// The full deterministic agent archetype catalog for the Agent Builder Engine.
// Every archetype has a fixed capability set, tool list, communication config,
// and default actions — so the same vision always produces the same agent fleet.
// ═══════════════════════════════════════════════════════════════════════════

export interface AgentArchetype {
  id: string;
  name: string;
  short_name: string;
  category: string;
  icon: string;
  description: string;
  persona_type: string;
  capabilities: string[];
  tools: string[];
  communication: {
    sms: boolean;
    mms: boolean;
    email: boolean;
    voice: boolean;
    whatsapp: boolean;
  };
  google_workspace: {
    calendar: boolean;
    tasks: boolean;
    gmail: boolean;
    drive: boolean;
    sheets: boolean;
    docs: boolean;
  };
  cloud_browser: {
    enabled: boolean;
    headless: boolean;
    max_sessions: number;
  };
  api_access_level: 'full' | 'read_only' | 'limited' | 'custom';
  memory_categories: string[];
  model_preference: string;
  max_autonomy: 'advisory' | 'supervised' | 'autonomous' | 'full_autonomous';
  default_actions: { title: string; category: string; description: string }[];
}

export const AGENT_TAXONOMY: AgentArchetype[] = [
  // ── Leadership & Strategy ──────────────────────────────────────────────
  {
    id: 'orchestrator',
    name: 'Orchestrator',
    short_name: 'ORC',
    category: 'leadership',
    icon: 'Network',
    description: 'Master coordinator that routes tasks across the entire agent swarm, resolves dependencies, and ensures deterministic execution.',
    persona_type: 'orchestrator',
    capabilities: ['entity_crud', 'function_invoke', 'agent_coordination', 'workflow_trigger', 'approval_routing'],
    tools: ['swarmOrchestrator', 'metaAgent', 'convergenceEngine', 'autoComplete'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: true, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'full',
    memory_categories: ['general', 'process', 'decision', 'conversation'],
    model_preference: 'claude-sonnet-5',
    max_autonomy: 'full_autonomous',
    default_actions: [
      { title: 'Coordinate swarm task routing', category: 'orchestration', description: 'Receive incoming goals and route to appropriate specialist agents' },
      { title: 'Resolve dependency conflicts', category: 'orchestration', description: 'Detect and resolve task dependencies across agents' },
    ],
  },
  {
    id: 'ceo',
    name: 'CEO Agent',
    short_name: 'CEO',
    category: 'leadership',
    icon: 'Crown',
    description: 'Executive decision-maker that sets strategic direction, approves major actions, and represents the owner\'s intent.',
    persona_type: 'ceo',
    capabilities: ['entity_crud', 'function_invoke', 'approval_routing', 'strategy'],
    tools: ['metaAgent', 'convergenceEngine', 'fleetAlphaPrime'],
    communication: { sms: false, mms: false, email: true, voice: true, whatsapp: false },
    google_workspace: { calendar: true, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'full',
    memory_categories: ['general', 'decision', 'strategy', 'conversation'],
    model_preference: 'claude-sonnet-5',
    max_autonomy: 'full_autonomous',
    default_actions: [
      { title: 'Strategic decision review', category: 'leadership', description: 'Review and approve/reject major strategic decisions' },
      { title: 'Executive audit', category: 'audit', description: 'Run full-system executive audit and report to owner' },
    ],
  },
  {
    id: 'strategist',
    name: 'Strategist',
    short_name: 'STR',
    category: 'leadership',
    icon: 'Compass',
    description: 'Market analysis, competitive intelligence, and strategic planning agent that produces actionable roadmaps.',
    persona_type: 'strategy',
    capabilities: ['function_invoke', 'entity_read', 'research', 'web_search'],
    tools: ['scanCompetitors', 'tradeCrystalBall', 'companyIntel', 'domainGoldRush'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: true, headless: true, max_sessions: 3 },
    api_access_level: 'read_only',
    memory_categories: ['market_intel', 'competitor_intel', 'decision', 'process'],
    model_preference: 'gemini_3_flash',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Competitive landscape analysis', category: 'research', description: 'Scan competitors and produce competitive intelligence report' },
      { title: 'Strategic roadmap generation', category: 'planning', description: 'Generate 30/60/90 day strategic roadmap' },
    ],
  },
  {
    id: 'visionary',
    name: 'Visionary',
    short_name: 'VIS',
    category: 'leadership',
    icon: 'Eye',
    description: 'Future-planning agent that forecasts trends, identifies opportunities, and drives innovation.',
    persona_type: 'strategy',
    capabilities: ['function_invoke', 'web_search', 'research'],
    tools: ['tradeCrystalBall', 'companyIntel', 'domainGoldRush'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: false, gmail: true, drive: true, sheets: false, docs: true },
    cloud_browser: { enabled: true, headless: true, max_sessions: 2 },
    api_access_level: 'read_only',
    memory_categories: ['market_intel', 'decision', 'process'],
    model_preference: 'gemini_3_flash',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Trend forecasting', category: 'research', description: 'Identify emerging trends and opportunities in the industry' },
    ],
  },
  {
    id: 'planner',
    name: 'Planner',
    short_name: 'PLN',
    category: 'operations',
    icon: 'Calendar',
    description: 'Project planning agent that creates timelines, manages schedules, and tracks milestones.',
    persona_type: 'custom',
    capabilities: ['entity_crud', 'function_invoke', 'calendar_management'],
    tools: ['swarmOrchestrator', 'googleWorkspaceSync'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: true, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'limited',
    memory_categories: ['general', 'process', 'decision'],
    model_preference: 'automatic',
    max_autonomy: 'supervised',
    default_actions: [
      { title: 'Project timeline creation', category: 'scheduling', description: 'Create detailed project timeline with milestones' },
    ],
  },

  // ── Architecture & Engineering ──────────────────────────────────────────
  {
    id: 'architect',
    name: 'Architect',
    short_name: 'ARC',
    category: 'technical',
    icon: 'Cpu',
    description: 'System architecture agent that designs technical blueprints, data models, and integration patterns.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_read', 'code_generation', 'architecture'],
    tools: ['systemAuditor', 'graphEngine', 'metaAgent'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: false, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'read_only',
    memory_categories: ['technical', 'process', 'decision'],
    model_preference: 'claude-sonnet-5',
    max_autonomy: 'supervised',
    default_actions: [
      { title: 'Architecture design', category: 'code_change', description: 'Design system architecture and data models' },
      { title: 'Integration pattern selection', category: 'code_change', description: 'Select and document integration patterns' },
    ],
  },
  {
    id: 'engineer',
    name: 'Engineer',
    short_name: 'ENG',
    category: 'technical',
    icon: 'Code',
    description: 'Implementation agent that writes production code, fixes bugs, and deploys changes.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'code_generation', 'deployment'],
    tools: ['vercelDeploy', 'vercelManager', 'githubSync', 'supabaseMigrationDeploy'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: false, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'full',
    memory_categories: ['technical', 'process', 'lesson_learned'],
    model_preference: 'claude-sonnet-5',
    max_autonomy: 'supervised',
    default_actions: [
      { title: 'Feature implementation', category: 'code_change', description: 'Implement features from specification' },
      { title: 'Bug repair', category: 'repair', description: 'Diagnose and fix reported bugs' },
    ],
  },
  {
    id: 'frontend_creator',
    name: 'Frontend Creator',
    short_name: 'FE',
    category: 'technical',
    icon: 'Palette',
    description: 'UI/UX design and frontend development agent that creates beautiful, responsive interfaces.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'code_generation', 'image_generation'],
    tools: ['vercelDeploy', 'generateImage', 'rebrandStudio'],
    communication: { sms: false, mms: false, email: false, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: false, drive: true, sheets: false, docs: true },
    cloud_browser: { enabled: true, headless: true, max_sessions: 2 },
    api_access_level: 'limited',
    memory_categories: ['technical', 'process'],
    model_preference: 'claude-sonnet-5',
    max_autonomy: 'supervised',
    default_actions: [
      { title: 'UI component creation', category: 'code_change', description: 'Create React components with Tailwind styling' },
      { title: 'Mockup generation', category: 'code_change', description: 'Generate frontend mockup images for design review' },
    ],
  },
  {
    id: 'backend_creator',
    name: 'Backend Creator',
    short_name: 'BE',
    category: 'technical',
    icon: 'Database',
    description: 'API and backend development agent that creates server functions, data pipelines, and integrations.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'code_generation', 'api_design'],
    tools: ['supabaseMigrationDeploy', 'graphEngine', 'ragPipeline'],
    communication: { sms: false, mms: false, email: false, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: false, drive: true, sheets: false, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'full',
    memory_categories: ['technical', 'process', 'lesson_learned'],
    model_preference: 'claude-sonnet-5',
    max_autonomy: 'supervised',
    default_actions: [
      { title: 'API endpoint creation', category: 'code_change', description: 'Create backend function endpoints' },
      { title: 'Data pipeline setup', category: 'code_change', description: 'Design and implement data pipelines' },
    ],
  },
  {
    id: 'autonomous_coder',
    name: 'Autonomous Coder',
    short_name: 'AC',
    category: 'technical',
    icon: 'Cpu',
    description: 'Self-directed coding agent that can plan, implement, test, and deploy features end-to-end with minimal supervision.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'code_generation', 'deployment', 'testing'],
    tools: ['vercelDeploy', 'githubSync', 'regressionTestSuite', 'postconditionValidator'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: false, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'full',
    memory_categories: ['technical', 'process', 'lesson_learned', 'decision'],
    model_preference: 'claude-sonnet-5',
    max_autonomy: 'full_autonomous',
    default_actions: [
      { title: 'End-to-end feature build', category: 'code_change', description: 'Plan, implement, test, and deploy a feature autonomously' },
    ],
  },

  // ── SEO & Digital Dominance ────────────────────────────────────────────
  {
    id: 'seo_agent',
    name: 'SEO & AEO Agent',
    short_name: 'SEO',
    category: 'marketing',
    icon: 'Search',
    description: 'Search engine and AI engine optimization agent that drives organic traffic and AI search visibility.',
    persona_type: 'seo',
    capabilities: ['function_invoke', 'entity_crud', 'web_search', 'content_generation'],
    tools: ['optimizeSeo', 'generateSeoPage', 'fillContentGaps', 'submitToIndexers', 'pingIndexNow', 'seoAeoSimulator', 'pullSearchConsoleData'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: true, headless: true, max_sessions: 3 },
    api_access_level: 'full',
    memory_categories: ['seo', 'market_intel', 'process'],
    model_preference: 'gemini_3_flash',
    max_autonomy: 'full_autonomous',
    default_actions: [
      { title: 'SEO audit and optimization', category: 'seo_optimization', description: 'Audit site SEO and apply optimizations' },
      { title: 'Content gap filling', category: 'content_creation', description: 'Identify and fill content gaps' },
      { title: 'Index submission', category: 'seo_optimization', description: 'Submit URLs to search engines and IndexNow' },
    ],
  },
  {
    id: 'digital_dominance',
    name: 'Digital Dominance Agent',
    short_name: 'DOM',
    category: 'marketing',
    icon: 'TrendingUp',
    description: 'Market dominance agent that floods niches with content, builds persona fame, and drives national scale.',
    persona_type: 'seo',
    capabilities: ['function_invoke', 'entity_crud', 'web_search', 'content_generation', 'deployment'],
    tools: ['dominanceEngine', 'domainGoldRush', 'generateSitemap', 'generateRss', 'swarmOrchestrator'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: true, headless: true, max_sessions: 5 },
    api_access_level: 'full',
    memory_categories: ['seo', 'market_intel', 'competitor_intel', 'process'],
    model_preference: 'gemini_3_flash',
    max_autonomy: 'full_autonomous',
    default_actions: [
      { title: 'Dominance campaign launch', category: 'deployment', description: 'Launch full digital dominance campaign for a niche' },
      { title: 'Content flood execution', category: 'content_creation', description: 'Generate and deploy 500+ SEO pages' },
    ],
  },
  {
    id: 'multiplier',
    name: 'Multiplier',
    short_name: 'MLT',
    category: 'leadership',
    icon: 'Zap',
    description: 'Growth multiplication agent that creates viral mechanics, network effects, and scale loops.',
    persona_type: 'strategy',
    capabilities: ['function_invoke', 'entity_read', 'web_search', 'research'],
    tools: ['tradeCrystalBall', 'companyIntel', 'domainGoldRush'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: true, headless: true, max_sessions: 2 },
    api_access_level: 'read_only',
    memory_categories: ['market_intel', 'decision', 'process'],
    model_preference: 'gemini_3_flash',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Growth loop design', category: 'research', description: 'Design viral growth loops and network effects' },
    ],
  },

  // ── Communications ──────────────────────────────────────────────────────
  {
    id: 'social_media',
    name: 'Social Media Agent',
    short_name: 'SOC',
    category: 'marketing',
    icon: 'Share2',
    description: 'Social content creation, scheduling, engagement, and brand monitoring across all platforms.',
    persona_type: 'social_media',
    capabilities: ['function_invoke', 'entity_crud', 'content_generation', 'image_generation', 'browser_automation'],
    tools: ['socialStudio', 'swarmOrchestrator', 'generateImage', 'syncContentCalendar'],
    communication: { sms: false, mms: true, email: false, voice: false, whatsapp: false },
    google_workspace: { calendar: true, tasks: true, gmail: false, drive: true, sheets: true, docs: false },
    cloud_browser: { enabled: true, headless: false, max_sessions: 5 },
    api_access_level: 'full',
    memory_categories: ['general', 'process', 'conversation'],
    model_preference: 'gemini_3_flash',
    max_autonomy: 'full_autonomous',
    default_actions: [
      { title: 'Daily social posts', category: 'social_media', description: 'Generate and publish 3x daily social posts' },
      { title: 'Engagement monitoring', category: 'social_media', description: 'Monitor and respond to social engagement' },
    ],
  },
  {
    id: 'sms_operator',
    name: 'SMS/MMS Operator',
    short_name: 'SMS',
    category: 'communications',
    icon: 'MessageSquare',
    description: 'SMS and MMS messaging agent for lead follow-up, appointment reminders, and customer communication.',
    persona_type: 'communications',
    capabilities: ['function_invoke', 'entity_crud', 'communication'],
    tools: ['xtremeComms', 'sendFollowUpEmail', 'bookEstimate'],
    communication: { sms: true, mms: true, email: false, voice: false, whatsapp: true },
    google_workspace: { calendar: true, tasks: true, gmail: false, drive: false, sheets: true, docs: false },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'limited',
    memory_categories: ['client_history', 'conversation', 'process'],
    model_preference: 'automatic',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Lead SMS follow-up', category: 'communication', description: 'Send automated SMS follow-ups to new leads' },
      { title: 'Appointment reminders', category: 'communication', description: 'Send appointment reminder messages' },
    ],
  },
  {
    id: 'whatsapp_operator',
    name: 'WhatsApp Operator',
    short_name: 'WAP',
    category: 'communications',
    icon: 'MessageCircle',
    description: 'WhatsApp messaging agent for international communication and customer support.',
    persona_type: 'communications',
    capabilities: ['function_invoke', 'entity_crud', 'communication'],
    tools: ['xtremeComms', 'sendFollowUpEmail'],
    communication: { sms: false, mms: true, email: false, voice: false, whatsapp: true },
    google_workspace: { calendar: false, tasks: false, gmail: false, drive: false, sheets: true, docs: false },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'limited',
    memory_categories: ['client_history', 'conversation', 'process'],
    model_preference: 'automatic',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'WhatsApp lead response', category: 'communication', description: 'Respond to WhatsApp inquiries automatically' },
    ],
  },
  {
    id: 'voice_operator',
    name: 'AI Voice Operator',
    short_name: 'VOX',
    category: 'communications',
    icon: 'PhoneCall',
    description: 'AI voice agent for inbound/outbound calls, appointment booking, and voice-based customer interaction.',
    persona_type: 'voice',
    capabilities: ['function_invoke', 'entity_crud', 'communication', 'voice'],
    tools: ['voiceAssistant', 'bookEstimate', 'xtremeComms'],
    communication: { sms: false, mms: false, email: false, voice: true, whatsapp: false },
    google_workspace: { calendar: true, tasks: true, gmail: true, drive: false, sheets: true, docs: false },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'limited',
    memory_categories: ['client_history', 'conversation', 'process'],
    model_preference: 'automatic',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Inbound call handling', category: 'phone_call', description: 'Handle inbound calls and book appointments' },
      { title: 'Outbound follow-up calls', category: 'phone_call', description: 'Make outbound follow-up calls to leads' },
    ],
  },
  {
    id: 'google_workspace_op',
    name: 'Google Workspace Operator',
    short_name: 'GSW',
    category: 'operations',
    icon: 'Calendar',
    description: 'Google Workspace automation agent that manages Calendar, Tasks, Gmail, Drive, Sheets, and Docs.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'calendar_management', 'document_creation'],
    tools: ['googleWorkspaceSync', 'syncContentCalendar', 'syncLeadToSheet'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: true, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'limited',
    memory_categories: ['general', 'process', 'client_history'],
    model_preference: 'automatic',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Calendar sync', category: 'calendar_management', description: 'Sync appointments to Google Calendar' },
      { title: 'Lead sheet sync', category: 'data_analysis', description: 'Sync leads to Google Sheets' },
    ],
  },

  // ── Intelligence & Analytics ─────────────────────────────────────────────
  {
    id: 'vision_agent',
    name: 'Vision Agent',
    short_name: 'VIS-A',
    category: 'technical',
    icon: 'Eye',
    description: 'Computer vision agent that analyzes images, photos, and visual data for inspection and quality assessment.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'image_analysis', 'entity_crud'],
    tools: ['visionCortexRouter', 'shadowBrowse', 'generateImage'],
    communication: { sms: false, mms: true, email: false, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: false, gmail: false, drive: true, sheets: true, docs: false },
    cloud_browser: { enabled: true, headless: true, max_sessions: 3 },
    api_access_level: 'limited',
    memory_categories: ['technical', 'process', 'observation'],
    model_preference: 'gemini_3_flash',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Image analysis', category: 'data_analysis', description: 'Analyze uploaded images and extract structured data' },
    ],
  },
  {
    id: 'analytics_agent',
    name: 'Analytics Agent',
    short_name: 'ANL',
    category: 'technical',
    icon: 'BarChart3',
    description: 'Data analysis and reporting agent that tracks metrics, monitors KPIs, and produces insights.',
    persona_type: 'research',
    capabilities: ['function_invoke', 'entity_read', 'data_analysis', 'reporting'],
    tools: ['googleAnalytics', 'fetchCoreWebVitals', 'pullSearchConsoleData', 'graphEngine'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: false, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'read_only',
    memory_categories: ['general', 'process', 'observation'],
    model_preference: 'automatic',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Weekly analytics report', category: 'reporting', description: 'Generate weekly analytics report' },
      { title: 'KPI monitoring', category: 'monitoring', description: 'Monitor KPIs and alert on anomalies' },
    ],
  },
  {
    id: 'predictor',
    name: 'Predictor',
    short_name: 'PRD',
    category: 'technical',
    icon: 'TrendingUp',
    description: 'Predictive modeling agent that forecasts trends, revenue, and market movements using real data.',
    persona_type: 'research',
    capabilities: ['function_invoke', 'entity_read', 'data_analysis', 'web_search'],
    tools: ['tradeCrystalBall', 'googleAnalytics', 'companyIntel'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: false, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: true, headless: true, max_sessions: 2 },
    api_access_level: 'read_only',
    memory_categories: ['market_intel', 'decision', 'observation'],
    model_preference: 'gemini_3_flash',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Revenue forecast', category: 'data_analysis', description: 'Generate revenue forecast based on pipeline data' },
    ],
  },
  {
    id: 'finance_agent',
    name: 'Finance Agent',
    short_name: 'FIN',
    category: 'finance',
    icon: 'DollarSign',
    description: 'Financial planning agent that manages budgets, tracks P&L, and produces financial reports.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_read', 'data_analysis', 'reporting'],
    tools: ['googleAnalytics', 'graphEngine'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: false, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'read_only',
    memory_categories: ['general', 'decision', 'process'],
    model_preference: 'automatic',
    max_autonomy: 'supervised',
    default_actions: [
      { title: 'Budget tracking', category: 'reporting', description: 'Track budget vs actuals' },
      { title: 'P&L report', category: 'reporting', description: 'Generate monthly P&L report' },
    ],
  },
  {
    id: 'discovery_agent',
    name: 'Discovery Agent',
    short_name: 'DSC',
    category: 'research',
    icon: 'Search',
    description: 'Research and sourcing agent that finds information, tools, and opportunities across the web.',
    persona_type: 'research',
    capabilities: ['function_invoke', 'web_search', 'browser_automation', 'entity_crud'],
    tools: ['shadowBrowse', 'companyIntel', 'scanCompetitors', 'domainGoldRush'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: true, headless: true, max_sessions: 5 },
    api_access_level: 'read_only',
    memory_categories: ['market_intel', 'competitor_intel', 'process', 'observation'],
    model_preference: 'gemini_3_flash',
    max_autonomy: 'full_autonomous',
    default_actions: [
      { title: 'Market research', category: 'research', description: 'Research market opportunities and competitors' },
      { title: 'Tool discovery', category: 'research', description: 'Find and evaluate tools and services' },
    ],
  },

  // ── Operations & Maintenance ─────────────────────────────────────────────
  {
    id: 'maintenance_agent',
    name: 'Maintenance Agent',
    short_name: 'MNT',
    category: 'operations',
    icon: 'Wrench',
    description: 'System monitoring and upkeep agent that ensures 24/7 health, runs preventive maintenance, and auto-repairs.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'monitoring', 'repair'],
    tools: ['siteHealthChecker', 'systemAuditor', 'autoComplete', 'convergenceEngine', 'recursiveHealingEngine'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: false, sheets: true, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'full',
    memory_categories: ['technical', 'process', 'lesson_learned'],
    model_preference: 'automatic',
    max_autonomy: 'full_autonomous',
    default_actions: [
      { title: 'System health check', category: 'monitoring', description: 'Run full system health check' },
      { title: 'Auto-repair', category: 'repair', description: 'Auto-repair detected issues' },
    ],
  },
  {
    id: 'documentor',
    name: 'Document Creator',
    short_name: 'DOC',
    category: 'operations',
    icon: 'FileText',
    description: 'Documentation agent that creates SOPs, build docs, knowledge bases, and process documentation.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'document_creation', 'content_generation'],
    tools: ['generateSop', 'intelligenceSync', 'ragPipeline'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: false, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'limited',
    memory_categories: ['general', 'process', 'policy'],
    model_preference: 'claude-sonnet-5',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'SOP creation', category: 'reporting', description: 'Create standard operating procedures' },
      { title: 'Build doc generation', category: 'reporting', description: 'Generate build documentation' },
    ],
  },
  {
    id: 'trainer',
    name: 'Trainer',
    short_name: 'TRN',
    category: 'operations',
    icon: 'GraduationCap',
    description: 'Training agent that creates training programs, assesses skills, and develops agent capabilities.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'content_generation'],
    tools: ['generateSop', 'intelligenceSync'],
    communication: { sms: false, mms: false, email: true, voice: true, whatsapp: false },
    google_workspace: { calendar: true, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'limited',
    memory_categories: ['general', 'process', 'skill'],
    model_preference: 'automatic',
    max_autonomy: 'supervised',
    default_actions: [
      { title: 'Training program creation', category: 'reporting', description: 'Create training programs for agents and staff' },
    ],
  },
  {
    id: 'replicator',
    name: 'Replicator',
    short_name: 'REP',
    category: 'operations',
    icon: 'Copy',
    description: 'System cloning agent that replicates entire agent fleets, sites, and workflows for new niches or markets.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'deployment'],
    tools: ['rebrandStudio', 'dominanceEngine', 'swarmOrchestrator'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: true, headless: true, max_sessions: 3 },
    api_access_level: 'full',
    memory_categories: ['general', 'process', 'decision'],
    model_preference: 'automatic',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Fleet replication', category: 'deployment', description: 'Clone agent fleet for new niche or market' },
    ],
  },
  {
    id: 'networker',
    name: 'Networker',
    short_name: 'NET',
    category: 'sales',
    icon: 'Users',
    description: 'Relationship building agent that develops partnerships, manages contacts, and expands networks.',
    persona_type: 'lead',
    capabilities: ['function_invoke', 'entity_crud', 'communication', 'web_search'],
    tools: ['pushLeadToHubspot', 'syncLeadToSheet', 'companyIntel'],
    communication: { sms: true, mms: false, email: true, voice: true, whatsapp: true },
    google_workspace: { calendar: true, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: true, headless: false, max_sessions: 3 },
    api_access_level: 'limited',
    memory_categories: ['client_history', 'conversation', 'process'],
    model_preference: 'automatic',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Partnership outreach', category: 'communication', description: 'Reach out to potential partners' },
    ],
  },

  // ── Browser & Shadow ────────────────────────────────────────────────────
  {
    id: 'headless_browser',
    name: 'Headless Browser Agent',
    short_name: 'HBR',
    category: 'technical',
    icon: 'Globe',
    description: 'Headless browser automation agent for scraping, data extraction, and automated form filling at scale.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'browser_automation', 'entity_crud'],
    tools: ['shadowBrowse', 'railwayScraper', 'skipTrace'],
    communication: { sms: false, mms: false, email: false, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: false, gmail: false, drive: true, sheets: true, docs: false },
    cloud_browser: { enabled: true, headless: true, max_sessions: 10 },
    api_access_level: 'limited',
    memory_categories: ['technical', 'process', 'observation'],
    model_preference: 'automatic',
    max_autonomy: 'full_autonomous',
    default_actions: [
      { title: 'Web scraping', category: 'browser_automation', description: 'Scrape data from target websites' },
    ],
  },
  {
    id: 'headful_browser',
    name: 'Headful Browser Agent',
    short_name: 'HFB',
    category: 'technical',
    icon: 'Globe',
    description: 'Headful browser automation agent for interactive sessions, social media management, and form-heavy workflows.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'browser_automation', 'entity_crud'],
    tools: ['shadowBrowse', 'socialStudio'],
    communication: { sms: false, mms: false, email: false, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: false, gmail: false, drive: true, sheets: true, docs: false },
    cloud_browser: { enabled: true, headless: false, max_sessions: 5 },
    api_access_level: 'limited',
    memory_categories: ['technical', 'process', 'observation'],
    model_preference: 'automatic',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Interactive browsing', category: 'browser_automation', description: 'Navigate and interact with websites' },
    ],
  },
  {
    id: 'shadow_agent',
    name: 'Shadow Agent',
    short_name: 'SHD',
    category: 'leadership',
    icon: 'EyeOff',
    description: 'Covert operations agent that executes tasks tracelessly, with full access and no visible footprint.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'browser_automation', 'communication', 'code_generation', 'deployment'],
    tools: ['shadowBrowse', 'visionCortexRouter', 'swarmOrchestrator', 'metaAgent', 'convergenceEngine', 'autoComplete'],
    communication: { sms: true, mms: true, email: true, voice: true, whatsapp: true },
    google_workspace: { calendar: true, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: true, headless: false, max_sessions: 10 },
    api_access_level: 'full',
    memory_categories: ['general', 'technical', 'market_intel', 'competitor_intel', 'decision', 'process', 'conversation', 'lesson_learned', 'skill'],
    model_preference: 'claude-sonnet-5',
    max_autonomy: 'full_autonomous',
    default_actions: [
      { title: 'Covert operation', category: 'custom', description: 'Execute covert operation with no trace' },
      { title: 'Full-system access', category: 'custom', description: 'Access all entities, functions, and browser' },
    ],
  },

  // ── Validation & Quality ────────────────────────────────────────────────
  {
    id: 'validator',
    name: 'Validator Agent',
    short_name: 'VLD',
    category: 'operations',
    icon: 'Shield',
    description: 'Quality assurance agent that validates builds, runs tests, lints code, and ensures production readiness.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_read', 'testing', 'validation'],
    tools: ['regressionTestSuite', 'postconditionValidator', 'systemAuditor', 'autoComplete', 'convergenceEngine'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: true, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'read_only',
    memory_categories: ['technical', 'process', 'lesson_learned'],
    model_preference: 'automatic',
    max_autonomy: 'autonomous',
    default_actions: [
      { title: 'Build validation', category: 'audit', description: 'Validate build passes all checks' },
      { title: 'Lint and test', category: 'audit', description: 'Run linter and test suite' },
    ],
  },
  {
    id: 'api_agent',
    name: 'API Agent',
    short_name: 'API',
    category: 'technical',
    icon: 'Key',
    description: 'API management agent that creates, manages, and secures API endpoints and keys.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'api_design'],
    tools: ['apiKeyManager', 'graphEngine'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: false, gmail: true, drive: true, sheets: true, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'full',
    memory_categories: ['technical', 'process', 'policy'],
    model_preference: 'automatic',
    max_autonomy: 'supervised',
    default_actions: [
      { title: 'API key management', category: 'code_change', description: 'Create and manage API keys' },
    ],
  },
  {
    id: 'mcp_agent',
    name: 'MCP Agent',
    short_name: 'MCP',
    category: 'technical',
    icon: 'Network',
    description: 'MCP server management agent that exposes system capabilities to external AI clients.',
    persona_type: 'custom',
    capabilities: ['function_invoke', 'entity_crud', 'api_design'],
    tools: ['graphEngine', 'ragPipeline'],
    communication: { sms: false, mms: false, email: true, voice: false, whatsapp: false },
    google_workspace: { calendar: false, tasks: false, gmail: true, drive: true, sheets: false, docs: true },
    cloud_browser: { enabled: false, headless: true, max_sessions: 1 },
    api_access_level: 'full',
    memory_categories: ['technical', 'process'],
    model_preference: 'automatic',
    max_autonomy: 'supervised',
    default_actions: [
      { title: 'MCP server config', category: 'code_change', description: 'Configure MCP server endpoints' },
    ],
  },
];

// ── Sync targets for bidirectional sync ──────────────────────────────────
export const SYNC_TARGETS = [
  { id: 'chatgpt', name: 'ChatGPT Account', description: 'Sync agent prompts and conversations with your ChatGPT account', required: false },
  { id: 'google_drive', name: 'Google Drive', description: 'Store and sync agent files, docs, and intelligence', required: true },
  { id: 'supabase', name: 'Supabase', description: 'Durable nervous system, queues, and database', required: true },
  { id: 'vercel', name: 'Vercel', description: 'Deployment and orchestration platform', required: true },
  { id: 'github', name: 'GitHub', description: 'Source code repository and CI/CD', required: true },
  { id: 'railway', name: 'Railway', description: 'Persistent workers and background jobs', required: false },
];

// ── Get archetype by ID ───────────────────────────────────────────────────
export function getArchetype(id: string): AgentArchetype | undefined {
  return AGENT_TAXONOMY.find(a => a.id === id);
}

// ── Get all archetype IDs ────────────────────────────────────────────────
export function getAllArchetypeIds(): string[] {
  return AGENT_TAXONOMY.map(a => a.id);
}