// ════════════════════════════════════════════════════════════════
// ALPHA PRIME BENCHMARK PACKS — V1.0
// The machine-readable benchmark constitution for epoxyquotenearme.com
// ════════════════════════════════════════════════════════════════

export interface BenchmarkDef {
  benchmark_id: string;
  category: string;
  name: string;
  description: string;
  target: string;
  measurement: string;
  comparator: string;
  severity: 'P0' | 'P1' | 'P2' | 'P3';
  mandatory: boolean;
  environment: string;
  data_source: string;
  validator: string;
  evidence_required: boolean;
  freshness_requirement: string;
  auto_repair_allowed: boolean;
  applicable_routes?: string[];
  applicable_workflows?: string[];
  applicable_entities?: string[];
  standard_source: string;
}

export function getBenchmarkPacks(): BenchmarkDef[] {
  const packs: BenchmarkDef[] = [
    // ── SOURCE TRUTH ──
    { benchmark_id: 'SRC-DOMAIN-001', category: 'source_truth', name: 'Canonical domain is epoxyquotenearme.com', description: 'The CanonicalSiteRegistry must have exactly one active record with canonical_domain = epoxyquotenearme.com', target: 'epoxyquotenearme.com', measurement: 'CanonicalSiteRegistry.canonical_domain', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'CanonicalSiteRegistry', validator: 'alphaPrimeBenchmarkGenerator', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, applicable_entities: ['CanonicalSiteRegistry'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'SRC-REGISTRY-001', category: 'source_truth', name: 'CanonicalSiteRegistry singleton', description: 'Exactly one active CanonicalSiteRegistry record exists', target: '1', measurement: 'count(CanonicalSiteRegistry)', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'CanonicalSiteRegistry', validator: 'alphaPrimeBenchmarkGenerator', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, applicable_entities: ['CanonicalSiteRegistry'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'SRC-LOCATIONS-001', category: 'source_truth', name: 'Location registry count matches approved count', description: 'CanonicalLocationRegistry count equals CanonicalSiteRegistry.approved_location_count', target: 'approved_location_count', measurement: 'count(CanonicalLocationRegistry)', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'CanonicalLocationRegistry,CanonicalSiteRegistry', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, applicable_entities: ['CanonicalLocationRegistry', 'CanonicalSiteRegistry'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'SRC-FACTS-001', category: 'source_truth', name: 'Verified business facts exist', description: 'At least 10 VerifiedBusinessFacts with status=verified', target: '>=10', measurement: 'count(VerifiedBusinessFacts where status=verified)', comparator: 'threshold', severity: 'P1', mandatory: true, environment: 'production', data_source: 'VerifiedBusinessFacts', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '24h', auto_repair_allowed: false, applicable_entities: ['VerifiedBusinessFacts'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'SRC-GSC-001', category: 'source_truth', name: 'GSC property not UNKNOWN', description: 'Google Search Console property is verified at runtime', target: 'not UNKNOWN', measurement: 'CanonicalSiteRegistry.google_search_console_property', comparator: 'not_equals', severity: 'P0', mandatory: true, environment: 'production', data_source: 'CanonicalSiteRegistry', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, applicable_entities: ['CanonicalSiteRegistry'], standard_source: 'Google Search Console' },
    { benchmark_id: 'SRC-GA4-001', category: 'source_truth', name: 'GA4 property not UNKNOWN', description: 'GA4 property ID is discovered at runtime', target: 'not UNKNOWN', measurement: 'CanonicalSiteRegistry.ga4_property_id', comparator: 'not_equals', severity: 'P0', mandatory: true, environment: 'production', data_source: 'CanonicalSiteRegistry', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, applicable_entities: ['CanonicalSiteRegistry'], standard_source: 'Google Analytics' },
    { benchmark_id: 'SRC-REPO-001', category: 'source_truth', name: 'GitHub repository not UNKNOWN', description: 'GitHub repository is connected and not UNKNOWN', target: 'not UNKNOWN', measurement: 'CanonicalSiteRegistry.github_repository', comparator: 'not_equals', severity: 'P1', mandatory: true, environment: 'production', data_source: 'CanonicalSiteRegistry', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, applicable_entities: ['CanonicalSiteRegistry'], standard_source: 'GitHub' },

    // ── PUBLIC WEBSITE ──
    { benchmark_id: 'WEB-HOME-001', category: 'public_website', name: 'Homepage returns 200', description: 'Homepage at / returns HTTP 200', target: '200', measurement: 'HTTP GET /', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, applicable_routes: ['/'], standard_source: 'HTTP' },
    { benchmark_id: 'WEB-ESTIMATE-001', category: 'public_website', name: 'Estimate page returns 200', description: '/estimate returns HTTP 200', target: '200', measurement: 'HTTP GET /estimate', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/estimate', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, applicable_routes: ['/estimate'], standard_source: 'HTTP' },
    { benchmark_id: 'WEB-FUNNEL-001', category: 'public_website', name: 'Funnel page returns 200', description: '/funnel returns HTTP 200', target: '200', measurement: 'HTTP GET /funnel', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/funnel', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, applicable_routes: ['/funnel'], standard_source: 'HTTP' },
    { benchmark_id: 'WEB-LOCATIONS-001', category: 'public_website', name: 'Locations page returns 200', description: '/locations returns HTTP 200', target: '200', measurement: 'HTTP GET /locations', comparator: 'exact_equality', severity: 'P1', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/locations', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, applicable_routes: ['/locations'], standard_source: 'HTTP' },
    { benchmark_id: 'WEB-CTA-001', category: 'public_website', name: 'Estimate CTA present on homepage', description: 'Homepage has a visible estimate CTA button', target: 'present', measurement: 'DOM query for CTA element', comparator: 'contains', severity: 'P1', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '15min', auto_repair_allowed: false, applicable_routes: ['/'], standard_source: 'UX' },
    { benchmark_id: 'WEB-404-001', category: 'public_website', name: 'Unknown route returns 404 page', description: 'Unknown route renders PageNotFound component', target: '404 page rendered', measurement: 'HTTP GET /nonexistent-route', comparator: 'contains', severity: 'P2', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/nonexistent-route-xyz', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, standard_source: 'HTTP' },
    { benchmark_id: 'WEB-CANONICAL-001', category: 'public_website', name: 'Correct canonical URL on homepage', description: 'Homepage canonical URL points to production domain, not preview', target: 'https://epoxyquotenearme.com/', measurement: 'DOM link[rel=canonical]', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, applicable_routes: ['/'], standard_source: 'Google Search' },

    // ── SECURITY ──
    { benchmark_id: 'SEC-LEAD-RLS-001', category: 'security', name: 'Lead entity has RLS', description: 'Lead entity restricts read/update/delete to admin role', target: 'rls.read.user_condition.role=admin', measurement: 'Lead.jsonc rls block', comparator: 'contains', severity: 'P0', mandatory: true, environment: 'production', data_source: 'base44/entities/Lead.jsonc', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '24h', auto_repair_allowed: false, applicable_entities: ['Lead'], standard_source: 'OWASP' },
    { benchmark_id: 'SEC-AUTH-001', category: 'security', name: 'Admin pages require authentication', description: 'All /admin/* routes are gated by ProtectedRoute or AdminLayout auth check', target: 'auth required', measurement: 'App.jsx route config', comparator: 'contains', severity: 'P0', mandatory: true, environment: 'production', data_source: 'src/App.jsx', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '24h', auto_repair_allowed: false, applicable_routes: ['/admin/*'], standard_source: 'OWASP' },
    { benchmark_id: 'SEC-PII-001', category: 'security', name: 'No PII in public API responses', description: 'Public API endpoints do not return Lead PII (name, email, phone, address)', target: 'no PII', measurement: 'API response inspection', comparator: 'not_contains', severity: 'P0', mandatory: true, environment: 'production', data_source: 'runtime', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, standard_source: 'OWASP' },
    { benchmark_id: 'SEC-SECRETS-001', category: 'security', name: 'No secrets in source code', description: 'No API keys, tokens, or secrets hardcoded in source files', target: 'no secrets in source', measurement: 'source code scan', comparator: 'not_contains', severity: 'P0', mandatory: true, environment: 'production', data_source: 'src/**', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '24h', auto_repair_allowed: false, standard_source: 'OWASP' },
    { benchmark_id: 'SEC-WEBHOOK-001', category: 'security', name: 'Webhook endpoints validate signatures', description: 'payments-webhook validates JWT signatures', target: 'signature validated', measurement: 'function code inspection', comparator: 'contains', severity: 'P0', mandatory: true, environment: 'production', data_source: 'base44/functions/payments-webhook/entry.ts', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '24h', auto_repair_allowed: false, standard_source: 'OWASP' },

    // ── SEO ──
    { benchmark_id: 'SEO-CANONICAL-001', category: 'seo', name: 'One canonical URL per approved page', description: 'Each approved location has exactly one canonical URL in the registry', target: '1:1 mapping', measurement: 'CanonicalLocationRegistry.canonical_url count', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'CanonicalLocationRegistry', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '6h', auto_repair_allowed: false, applicable_entities: ['CanonicalLocationRegistry'], standard_source: 'Google Search' },
    { benchmark_id: 'SEO-ROBOTS-001', category: 'seo', name: 'robots.txt references correct sitemap', description: 'robots.txt sitemap directive points to production domain sitemap', target: 'https://epoxyquotenearme.com/sitemap.xml', measurement: 'robots.txt content', comparator: 'contains', severity: 'P1', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/robots.txt', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, standard_source: 'Google Search' },
    { benchmark_id: 'SEO-SITEMAP-001', category: 'seo', name: 'Sitemap contains all canonical location URLs', description: 'Sitemap URL set equals CanonicalLocationRegistry URL set', target: 'registry URLs = sitemap URLs', measurement: 'sitemap.xml URL count vs registry count', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/sitemap.xml', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '6h', auto_repair_allowed: false, applicable_entities: ['CanonicalLocationRegistry'], standard_source: 'Google Search' },
    { benchmark_id: 'SEO-SITEMAP-CANONICAL-001', category: 'seo', name: 'Sitemap has no non-canonical state routes', description: 'Sitemap contains only 2-letter state code URLs, no full-state-name URLs', target: '0 non-canonical', measurement: 'sitemap URLs with full-state-name paths', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/sitemap.xml', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '6h', auto_repair_allowed: false, standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'SEO-META-001', category: 'seo', name: 'Each page has unique title and description', description: 'No two pages share the same meta title or description', target: 'all unique', measurement: 'meta tag inspection', comparator: 'unique', severity: 'P1', mandatory: true, environment: 'production', data_source: 'DOM meta tags', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '6h', auto_repair_allowed: false, standard_source: 'Google Search' },
    { benchmark_id: 'SEO-LOCAL-VALUE-001', category: 'seo', name: 'Location pages have city-specific content', description: 'Each location page mentions its specific city name in H1 and body', target: 'city name present', measurement: 'DOM H1 + body text', comparator: 'contains', severity: 'P1', mandatory: true, environment: 'production', data_source: 'location page DOM', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '6h', auto_repair_allowed: false, standard_source: 'Google Search' },

    // ── SEARCH / GOOGLE ──
    { benchmark_id: 'GSC-PROPERTY-001', category: 'search_google', name: 'GSC property verified at runtime', description: 'pullSearchConsoleData returns data without 403', target: 'data returned', measurement: 'pullSearchConsoleData function call', comparator: 'success', severity: 'P0', mandatory: true, environment: 'production', data_source: 'pullSearchConsoleData', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, standard_source: 'Google Search Console' },
    { benchmark_id: 'GSC-FRESHNESS-001', category: 'search_google', name: 'GSC data less than 24h old', description: 'Latest GSC data is within 24 hours', target: '<24h', measurement: 'latest GSC record age', comparator: 'threshold', severity: 'P1', mandatory: true, environment: 'production', data_source: 'Search Console data', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, standard_source: 'Google Search Console' },
    { benchmark_id: 'GA4-PROPERTY-001', category: 'search_google', name: 'GA4 property discovered at runtime', description: 'googleAnalytics function returns property ID', target: 'property ID returned', measurement: 'googleAnalytics function call', comparator: 'success', severity: 'P0', mandatory: true, environment: 'production', data_source: 'googleAnalytics', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, standard_source: 'Google Analytics' },

    // ── PERFORMANCE ──
    { benchmark_id: 'PERF-LCP-001', category: 'performance', name: 'LCP under 2.5s on homepage', description: 'Largest Contentful Paint on homepage is under 2.5 seconds', target: '<2500ms', measurement: 'Core Web Vitals LCP', comparator: 'threshold', severity: 'P1', mandatory: true, environment: 'production', data_source: 'fetchCoreWebVitals', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, applicable_routes: ['/'], standard_source: 'Google CrUX' },
    { benchmark_id: 'PERF-CLS-001', category: 'performance', name: 'CLS under 0.1 on homepage', description: 'Cumulative Layout Shift on homepage is under 0.1', target: '<0.1', measurement: 'Core Web Vitals CLS', comparator: 'threshold', severity: 'P1', mandatory: true, environment: 'production', data_source: 'fetchCoreWebVitals', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, applicable_routes: ['/'], standard_source: 'Google CrUX' },
    { benchmark_id: 'PERF-ERRORS-001', category: 'performance', name: 'Zero critical JS errors on homepage', description: 'Homepage loads with zero critical JavaScript errors', target: '0 errors', measurement: 'browser console errors', comparator: 'exact_equality', severity: 'P1', mandatory: true, environment: 'production', data_source: 'runtime', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '15min', auto_repair_allowed: false, applicable_routes: ['/'], standard_source: 'Web Standards' },

    // ── FUNNEL ──
    { benchmark_id: 'FUNNEL-START-001', category: 'funnel', name: 'funnel_started event fires once per session', description: 'FunnelEvent with event=funnel_started fires exactly once per session', target: '1 per session', measurement: 'FunnelEvent count per session_id', comparator: 'exact_equality', severity: 'P2', mandatory: true, environment: 'production', data_source: 'FunnelEvent', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: true, applicable_entities: ['FunnelEvent'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'FUNNEL-COMPLETE-001', category: 'funnel', name: 'Estimate completion creates Lead record', description: 'Completing the estimate funnel creates a Lead entity record', target: 'Lead created', measurement: 'Lead count after funnel completion', comparator: 'success', severity: 'P0', mandatory: true, environment: 'production', data_source: 'Lead entity', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '15min', auto_repair_allowed: false, applicable_entities: ['Lead'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'FUNNEL-EMAIL-001', category: 'funnel', name: 'Estimate email sends successfully', description: 'sendEstimateEmail function completes without error', target: 'email sent', measurement: 'sendEstimateEmail function call', comparator: 'success', severity: 'P1', mandatory: true, environment: 'production', data_source: 'sendEstimateEmail', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: true, standard_source: 'Alpha Prime Constitution' },

    // ── DATA QUALITY ──
    { benchmark_id: 'DATA-LEAD-SQFT-001', category: 'data_quality', name: 'Leads have square_footage populated', description: 'At least 80% of leads have square_footage > 0', target: '>=80%', measurement: 'Lead.square_footage > 0 ratio', comparator: 'threshold', severity: 'P1', mandatory: true, environment: 'production', data_source: 'Lead entity', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: true, applicable_entities: ['Lead'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'DATA-LEAD-ESTIMATE-001', category: 'data_quality', name: 'Leads have estimate data', description: 'At least 80% of leads have estimate_mid > 0', target: '>=80%', measurement: 'Lead.estimate_mid > 0 ratio', comparator: 'threshold', severity: 'P1', mandatory: true, environment: 'production', data_source: 'Lead entity', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: true, applicable_entities: ['Lead'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'DATA-DUPLICATES-001', category: 'data_quality', name: 'No duplicate WebsiteTemplate records', description: 'No two WebsiteTemplate records share the same canonical_url', target: '0 duplicates', measurement: 'WebsiteTemplate canonical_url duplication', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'WebsiteTemplate', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '6h', auto_repair_allowed: true, applicable_entities: ['WebsiteTemplate'], standard_source: 'Alpha Prime Constitution' },

    // ── SOURCE PARITY ──
    { benchmark_id: 'PARITY-COUNT-001', category: 'source_parity', name: 'Template count = Registry count = approved count', description: 'WebsiteTemplate count equals CanonicalLocationRegistry count equals approved_location_count', target: 'all equal', measurement: 'entity count comparison', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'WebsiteTemplate,CanonicalLocationRegistry,CanonicalSiteRegistry', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, applicable_entities: ['WebsiteTemplate', 'CanonicalLocationRegistry', 'CanonicalSiteRegistry'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'PARITY-GITHUB-001', category: 'source_parity', name: 'GitHub repo not stale', description: 'GitHub repository last commit is within 24 hours of Base44 source', target: '<24h stale', measurement: 'GitHub last commit date vs Base44', comparator: 'threshold', severity: 'P1', mandatory: true, environment: 'production', data_source: 'GitHub API', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, standard_source: 'GitHub' },
    { benchmark_id: 'PARITY-VERCEL-001', category: 'source_parity', name: 'Vercel deployment matches GitHub main', description: 'Vercel deployment SHA matches GitHub main branch SHA', target: 'SHA match', measurement: 'Vercel deployment SHA vs GitHub main SHA', comparator: 'exact_equality', severity: 'P1', mandatory: true, environment: 'production', data_source: 'Vercel API, GitHub API', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, standard_source: 'Vercel' },

    // ── SWARM ──
    { benchmark_id: 'SWARM-HEARTBEAT-001', category: 'swarm', name: 'Heartbeat fires every 5 minutes', description: 'AlphaPrimeHeartbeat has a record within the last 10 minutes', target: '<10min since last heartbeat', measurement: 'AlphaPrimeHeartbeat latest created_date', comparator: 'threshold', severity: 'P0', mandatory: true, environment: 'production', data_source: 'AlphaPrimeHeartbeat', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, applicable_entities: ['AlphaPrimeHeartbeat'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'SWARM-FALSE-GREEN-001', category: 'swarm', name: 'Zero false-green SwarmAudit records', description: 'No SwarmAudit with status=fixed and fix_result containing failure indicators', target: '0 false-green', measurement: 'SwarmAudit where status=fixed AND fix_result matches failure pattern', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'SwarmAudit', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: true, applicable_entities: ['SwarmAudit'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'SWARM-TASK-COMPLETION-001', category: 'swarm', name: 'Tasks complete within max_retries', description: 'No SwarmTask with retry_count >= max_retries and status != failed', target: '0 stuck tasks', measurement: 'SwarmTask where retry_count >= max_retries AND status != failed', comparator: 'exact_equality', severity: 'P1', mandatory: true, environment: 'production', data_source: 'SwarmTask', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '15min', auto_repair_allowed: true, applicable_entities: ['SwarmTask'], standard_source: 'Alpha Prime Constitution' },

    // ── AUDIT SYSTEM ──
    { benchmark_id: 'AUDIT-TRIGGERS-001', category: 'audit_system', name: 'Audit triggers firing on schedule', description: 'AlphaPrimeAuditLedger has a record within the last 30 minutes', target: '<30min since last audit', measurement: 'AlphaPrimeAuditLedger latest created_date', comparator: 'threshold', severity: 'P0', mandatory: true, environment: 'production', data_source: 'AlphaPrimeAuditLedger', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '15min', auto_repair_allowed: false, applicable_entities: ['AlphaPrimeAuditLedger'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'AUDIT-INTEGRITY-001', category: 'audit_system', name: 'Audit system integrity score above 80', description: 'AuditSystemIntegrityScore.overall_score >= 80', target: '>=80', measurement: 'AuditSystemIntegrityScore.overall_score', comparator: 'threshold', severity: 'P0', mandatory: true, environment: 'production', data_source: 'AuditSystemIntegrityScore', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '15min', auto_repair_allowed: true, applicable_entities: ['AuditSystemIntegrityScore'], standard_source: 'Alpha Prime Constitution' },

    // ── CONNECTOR ──
    { benchmark_id: 'CONN-DRIVE-001', category: 'connector', name: 'Google Drive connector connected', description: 'googledrive connector getConnection() succeeds', target: 'CONNECTED', measurement: 'connectors.getConnection(googledrive)', comparator: 'success', severity: 'P1', mandatory: true, environment: 'production', data_source: 'connector API', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, standard_source: 'Google Workspace' },
    { benchmark_id: 'CONN-SHEETS-001', category: 'connector', name: 'Google Sheets connector connected', description: 'googlesheets connector getConnection() succeeds', target: 'CONNECTED', measurement: 'connectors.getConnection(googlesheets)', comparator: 'success', severity: 'P1', mandatory: true, environment: 'production', data_source: 'connector API', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, standard_source: 'Google Workspace' },
    { benchmark_id: 'CONN-GSC-001', category: 'connector', name: 'Google Search Console connector connected', description: 'google_search_console connector getConnection() succeeds', target: 'CONNECTED', measurement: 'connectors.getConnection(google_search_console)', comparator: 'success', severity: 'P0', mandatory: true, environment: 'production', data_source: 'connector API', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, standard_source: 'Google Search Console' },

    // ── COST ──
    { benchmark_id: 'COST-MODEL-001', category: 'cost', name: 'AI model cost tracked', description: 'AI model usage cost is tracked per cycle', target: 'cost tracked', measurement: 'cost tracking system', comparator: 'exists', severity: 'P2', mandatory: true, environment: 'production', data_source: 'cost tracking', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '24h', auto_repair_allowed: true, standard_source: 'Alpha Prime Constitution' },

    // ── BUSINESS OUTCOMES ──
    { benchmark_id: 'BIZ-LEADS-001', category: 'business_outcomes', name: 'Lead count tracked', description: 'Total lead count is available and tracked', target: 'count available', measurement: 'Lead entity count', comparator: 'exists', severity: 'P2', mandatory: true, environment: 'production', data_source: 'Lead entity', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, applicable_entities: ['Lead'], standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'BIZ-REVENUE-001', category: 'business_outcomes', name: 'Revenue attribution tracked', description: 'Won lead revenue is tracked and attributed', target: 'revenue tracked', measurement: 'Lead.won_value sum where status=WON', comparator: 'exists', severity: 'P2', mandatory: true, environment: 'production', data_source: 'Lead entity', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, applicable_entities: ['Lead'], standard_source: 'Alpha Prime Constitution' },

    // ── DEPLOYMENT ──
    { benchmark_id: 'DEPLOY-LIVE-001', category: 'deployment', name: 'Live site serves production canonical', description: 'Live site canonical URL points to epoxyquotenearme.com, not preview', target: 'https://epoxyquotenearme.com/', measurement: 'live site DOM canonical link', comparator: 'exact_equality', severity: 'P0', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '5min', auto_repair_allowed: false, standard_source: 'Alpha Prime Constitution' },
    { benchmark_id: 'DEPLOY-ROBOTS-001', category: 'deployment', name: 'Live robots.txt has no old-domain references', description: 'robots.txt does not reference epoxygaragefloorestimate.com', target: 'no old domain', measurement: 'robots.txt content', comparator: 'not_contains', severity: 'P0', mandatory: true, environment: 'production', data_source: 'https://epoxyquotenearme.com/robots.txt', validator: 'calculateDistanceTo100', evidence_required: true, freshness_requirement: '1h', auto_repair_allowed: false, standard_source: 'Alpha Prime Constitution' },
  ];

  return packs;
}