import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Activity, Bot, RefreshCw, ShieldCheck, Sparkles, Workflow, XCircle, Zap } from 'lucide-react';

const tone = { completed: 'text-emerald-300 bg-emerald-400/10', in_progress: 'text-cyan-300 bg-cyan-400/10', pending: 'text-amber-300 bg-amber-400/10', failed: 'text-red-300 bg-red-400/10', blocked: 'text-orange-300 bg-orange-400/10', retesting: 'text-violet-300 bg-violet-400/10' };
const Badge = ({ value }) => <span className={`rounded-full px-2.5 py-1 text-[10px] font-mono uppercase ${tone[value] || 'text-zinc-400 bg-white/5'}`}>{value || 'unknown'}</span>;

export default function AgentOps() {
  const status = useQuery({ queryKey: ['agent-os-status'], queryFn: () => base44.functions.invoke('swarmOrchestrator', { action: 'getStatus' }).then((r) => r.data), refetchInterval: 15000 });
  const tasks = useQuery({ queryKey: ['agent-os-tasks'], queryFn: () => base44.entities.SwarmTask.list('-created_date', 60), refetchInterval: 10000 });
  const personas = useQuery({ queryKey: ['agent-os-personas'], queryFn: () => base44.entities.AgentPersona.list('-created_date', 40), refetchInterval: 30000 });
  const audits = useQuery({ queryKey: ['agent-os-audits'], queryFn: () => base44.entities.SwarmAudit.list('-created_date', 24), refetchInterval: 30000 });
  const rows = tasks.data || [], agents = personas.data || [], auditRows = audits.data || [];
  const counts = rows.reduce((a, t) => ({ ...a, [t.status]: (a[t.status] || 0) + 1 }), {});
  const refresh = () => { status.refetch(); tasks.refetch(); personas.refetch(); audits.refetch(); };

  return <div className="min-h-screen bg-[#090b10] text-zinc-100"><header className="sticky top-0 z-40 border-b border-white/[.07] bg-[#090b10]/90 backdrop-blur-xl"><div className="max-w-[1600px] mx-auto h-16 px-5 flex items-center gap-3"><a href="/smai" className="flex items-center gap-2"><div className="h-9 w-9 rounded-xl bg-cyan-300/10 grid place-items-center"><Sparkles className="h-4 w-4 text-cyan-300" /></div><div><div className="text-sm font-bold">Strategic Minds AI</div><div className="text-[10px] text-zinc-600">AGENT OPERATIONS</div></div></a><a href="/smai/command" className="ml-8 text-xs text-zinc-500 hover:text-white">Command</a><button onClick={refresh} className="ml-auto flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs text-zinc-400"><RefreshCw className="h-3.5 w-3.5" /> Refresh</button></div></header>
  <main className="max-w-[1600px] mx-auto px-5 py-8"><section className="rounded-[2rem] border border-white/[.08] bg-gradient-to-br from-[#121722] to-[#0b0d12] p-7 md:p-10"><div className="grid xl:grid-cols-[1.3fr_.7fr] gap-8 items-end"><div><div className="inline-flex items-center gap-2 rounded-full bg-emerald-400/[.07] px-3 py-1.5 text-[10px] font-mono text-emerald-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300 animate-pulse" /> LIVE CONTROL PLANE</div><h1 className="mt-5 text-4xl md:text-6xl font-black tracking-[-.05em]">Parallel work, visible.</h1><p className="mt-4 max-w-2xl text-zinc-400 leading-7">A read-oriented view over the existing Digital Dominance swarm. Inspect agents, queue state, audits, and active work while protected mutation stays in admin.</p></div><div className="grid grid-cols-2 gap-3">{[['Agents', agents.length, Bot], ['Tasks', rows.length, Workflow], ['Pending', counts.pending || 0, Activity], ['Failures', (counts.failed || 0) + (counts.blocked || 0), XCircle]].map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-white/[.08] bg-white/[.035] p-4"><Icon className="h-4 w-4 text-cyan-300" /><div className="mt-4 text-3xl font-black">{value}</div><div className="text-xs text-zinc-600">{label}</div></div>)}</div></div></section>
  <section className="mt-6 grid xl:grid-cols-[1.2fr_.8fr] gap-6"><div className="rounded-3xl border border-white/[.08] bg-[#0e1117] overflow-hidden"><div className="px-5 py-4 border-b border-white/[.07] flex items-center gap-2"><Activity className="h-4 w-4 text-cyan-300" /><h2 className="font-bold">Task stream</h2></div><div className="divide-y divide-white/[.055] max-h-[760px] overflow-y-auto">{rows.map((task) => <div key={task.id} className="px-5 py-4"><div className="flex gap-3"><Zap className="mt-1 h-4 w-4 text-cyan-300 shrink-0" /><div className="min-w-0 flex-1"><div className="flex gap-3"><div className="font-medium text-sm flex-1">{task.title || task.description || 'Untitled task'}</div><Badge value={task.status} /></div><div className="mt-2 text-[11px] text-zinc-600">{task.assigned_agent || 'unassigned'} · {task.task_type || 'general'} · {task.priority || 'normal'}</div></div></div></div>)}</div></div>
  <div className="space-y-6"><div className="rounded-3xl border border-white/[.08] bg-[#0e1117] overflow-hidden"><div className="px-5 py-4 border-b border-white/[.07] flex items-center gap-2"><Bot className="h-4 w-4 text-cyan-300" /><h2 className="font-bold">Agent registry</h2></div><div className="max-h-[360px] overflow-y-auto divide-y divide-white/[.055]">{agents.map((agent) => <div key={agent.id} className="px-5 py-3.5 flex items-center gap-3"><div className="h-8 w-8 rounded-xl bg-cyan-300/[.06] grid place-items-center"><Bot className="h-3.5 w-3.5 text-cyan-300" /></div><div className="text-sm truncate">{agent.name || agent.role || 'Agent'}</div><span className="ml-auto h-2 w-2 rounded-full bg-emerald-400/70" /></div>)}</div></div>
  <div className="rounded-3xl border border-white/[.08] bg-[#0e1117] overflow-hidden"><div className="px-5 py-4 border-b border-white/[.07] flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-cyan-300" /><h2 className="font-bold">Validation pulse</h2></div><div className="p-4 space-y-2 max-h-[310px] overflow-y-auto">{auditRows.map((audit) => <div key={audit.id} className="rounded-xl bg-white/[.025] p-3 flex items-center gap-3"><div className="text-xs flex-1">{audit.summary || audit.created_date || 'Swarm audit'}</div><Badge value={audit.status} /></div>)}</div></div><div className="rounded-3xl border border-cyan-300/10 bg-cyan-300/[.035] p-5 text-xs leading-5 text-zinc-500"><ShieldCheck className="h-5 w-5 text-cyan-300 mb-3" />Production deploys, secrets, spend, destructive actions, customer messages, and permission changes stay behind governed admin approval surfaces.</div></div></section></main></div>;
}
